In [1]:
import numpy as np
import pandas as pd

1) Check if all elements from the following arrays return the logical value True:

In [2]:
A = np.array([[3, 2, 1, 4],
              [5, 2, 1, 6]])
 
B = np.array([[3, 2, 1, 4],
              [5, 2, 0, 6]])
 
C = np.array([[True, False, False],
              [True, True, True]])
 
D = np.array([0.1, 0.3])

In [4]:
for name, array in zip(list('ABCD'),[A,B,C,D]):
    print(f'{name}: {np.all(array)}')

A: True
B: False
C: False
D: True


2) Check if all elements from the following arrays return the logical value True along the axis with index 1:

In [2]:
A = np.array([[3, 2, 1, 4],
              [5, 2, 1, 6]])

B = np.array([[3, 2, 1, 4],
              [5, 2, 0, 6]])

C = np.array([[True, False, False],
              [True, True, True]])

In [3]:
  
for name, array in zip(list('ABC'), [A, B, C]):
    print(f'{name}: {np.all(array, axis=1)}')

A: [ True  True]
B: [ True False]
C: [False  True]


3) Check if any element of the following arrays returns the logical value True:

In [4]:
A = np.array([[0, 0, 0],
              [0, 0, 0]])

B = np.array([[0, 0, 0],
              [0, 1, 0]])

C = np.array([[False, False, False],
              [True, False, False]])

D = np.array([[0.1, 0.0]])

In [5]:
for name, array in zip(list('ABCD'), [A,B,C,D]):
    print(f'{name}: {np.any(array)}')

A: False
B: True
C: True
D: True


4) Check if any element of the following arrays returns the logical value True along the axis with index 0:

In [6]:
A = np.array([[0, 0, 0],
              [0, 0, 0]])

B = np.array([[0, 0, 0],
              [0, 1, 0]])

C = np.array([[False, False, False],
              [True, False, False]])

D = np.array([[0.1, 0.0]])

In [8]:
for name, array in zip(list('ABCD'), [A,B,C,D]):
    print(f'{name}: {np.any(array, axis=0)}')

A: [False False False]
B: [False  True False]
C: [ True False False]
D: [ True False]


5. Check if the following array has missing data (np.nan):

In [9]:
A = np.array([[3, 2, 1, np.nan],
              [5, np.nan, 1, 6]])

In [10]:
print(np.isnan(A))

[[False False False  True]
 [False  True False False]]


6) Check if the following arrays are equal (element-wise):

In [11]:
A = np.array([0.4, 0.5, 0.3])
B = np.array([0.39999999, 0.5000001, 0.3])

In [12]:
print(np.allclose(A,B))

True


7. Check if the following arrays are equal (element-wise):

In [13]:
A = np.array([0.4, 0.5, 0.3])
B = np.array([0.3999999999, 0.5000000001, 0.3])

In [14]:
print(A==B)

[False False  True]


8) Check which numbers (element-wise) from the A array are greater than numbers from the B array and print result to the console as shown below.

In [15]:
A = np.array([0.4, 0.5, 0.3, 0.9])
B = np.array([0.38, 0.51, 0.3, 0.91])

In [16]:
print(A>B)

[ True False False False]


9. Using Numpy create a 4x4 array filled with zeros (set data type to int). In response print this array to the console.

In [18]:
array = np.zeros((4,4), dtype='int')
print(array)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


10. Using Numpy, create an array 10x10 filled with number 255 and set the data type to float. Print this array to the console as shown below.


In [21]:
array = np.ones((10,10))*255.0
print(array)

[[255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]]


11. Using Numpy create a one-dimensional array of all two-digit numbers and print this array to the console as shown below.

In [26]:
print(np.arange(10,100,1))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81
 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]


12. Using Numpy create the following array:

In [ ]:
[[10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]

In [28]:
print(np.arange(10,100).reshape((9,10)))

[[10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


13. Using Numpy create a 6x6 two-dimensional array - identity matrix with int data type. Print this array to the console as shown below.

In [ ]:
[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]

In [29]:
print(np.eye(6,6,dtype='int'))

[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]


14. Set the random seed to 10. Then using Numpy create a one-dimensional array consisting of 30 pseudo-randomly generated values from the uniform distribution [0,1). Print result to the console as shown below.

In [31]:
np.random.seed(10)
print(np.random.rand(30))


[0.77132064 0.02075195 0.63364823 0.74880388 0.49850701 0.22479665
 0.19806286 0.76053071 0.16911084 0.08833981 0.68535982 0.95339335
 0.00394827 0.51219226 0.81262096 0.61252607 0.72175532 0.29187607
 0.91777412 0.71457578 0.54254437 0.14217005 0.37334076 0.67413362
 0.44183317 0.43401399 0.61776698 0.51313824 0.65039718 0.60103895]


15. Using Numpy create a two-dimensional array with the shape (10, 4) pseudo-randomly generated values from the standard normal distribution N(0,1). Set the random seed to 20. Print result to the console as shown below.

In [33]:
np.random.seed(20)
print(np.random.rand(10,4))

[[0.5881308  0.89771373 0.89153073 0.81583748]
 [0.03588959 0.69175758 0.37868094 0.51851095]
 [0.65795147 0.19385022 0.2723164  0.71860593]
 [0.78300361 0.85032764 0.77524489 0.03666431]
 [0.11669374 0.7512807  0.23921822 0.25480601]
 [0.85762553 0.94977903 0.56168686 0.17878052]
 [0.77025193 0.49238104 0.63125307 0.83949792]
 [0.4610394  0.49794007 0.67941112 0.65078591]
 [0.26879524 0.06732467 0.77144514 0.48098413]
 [0.32920641 0.51064106 0.26362883 0.31051155]]


16. Using Numpy create a two-dimensional array with the shape (10, 4) pseudo-randomly generated values from the normal distribution N(100, 5). Set the random seed to 30. Print result to the console as shown below.

In [36]:
np.random.rand(30)
sigma=np.sqrt(5)
mu=100
print(np.random.randn(10,4)*sigma+mu)

[[100.26994306 100.92578826 103.05559969  96.95174745]
 [100.03500265 102.02288173  98.19571431  98.42064204]
 [102.3543379   99.79099185  96.78240878  99.30398156]
 [101.80153119  99.97193525  99.41678224  98.01106732]
 [ 96.38673952  98.09494923  99.9079184   99.39553067]
 [ 96.63700335 102.93812139  99.93263598 101.41993241]
 [101.12347933 102.59823477  99.31632604 103.82878066]
 [102.61494062  99.38325919  94.38348759  99.06695186]
 [101.21099282  99.67553021  97.71567157 101.05604565]
 [ 98.41658771 103.16211201  98.90313451 102.64117836]]


17. The following array is given:
Iterate through this array and print each element to the console.

In [37]:
A = np.array([[1, 4, 3],
              [5, 2, 6]])

In [38]:
[print(i) for  i in np.nditer(A)]

1
4
3
5
2
6


[None, None, None, None, None, None]

18. Using Numpy create a one-dimensional array (vector) consisting of eleven equally distributed numbers from the [0,1] interval.

In [40]:
print(np.linspace(0,1,11))

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


19. Using Numpy create a one-dimensional array (vector) containing the possible result from the Big Lotto game. Set the random seed to 42. Print result to the console.

Tip: The result of this game is a 6-element vector of values from 1 to 49 inclusive.

In [41]:
np.random.seed(42)
print(np.random.choice(range(1,50), size=6, replace=False))

[14 46 48 45 18 28]


20. Using Numpy create the following two-dimensional array:

In [ ]:
[[0 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 2 0 0 0]
 [0 0 0 3 0 0]
 [0 0 0 0 4 0]
 [0 0 0 0 0 5]]

In [42]:
print(np.diag(np.arange(6)))

[[0 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 2 0 0 0]
 [0 0 0 3 0 0]
 [0 0 0 0 4 0]
 [0 0 0 0 0 5]]


21. Using Numpy create the following array. Save this array to a binary file named 'array.npy' and then load that file back into another variable. Print this variable to the console.

In [ ]:
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [47]:
array = np.arange(0,12,1).reshape(3,4)
np.save('array.npy', array)
array2=np.load('array.npy')
print(array2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


22. Using Numpy create the following array. Save this array to a text file named 'array.txt' with two decimal places and then load this file back into another variable. Print this variable to the console.


In [ ]:
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [49]:
A=np.arange(0,12).reshape(3,4)
np.savetxt('array.txt',array)
B=np.loadtxt('array.txt')
print(B)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]


23. Using Numpy create and convert the following array into the list. In response, print list to the console.

In [ ]:
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [52]:
array = np.arange(0,12)
l = array.tolist()
print(l)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]


24. Using the slice operator, transform this array into the following:

In [ ]:
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
array([[ 8,  9, 10, 11],
       [ 4,  5,  6,  7],
       [ 0,  1,  2,  3]])

In [55]:
array=np.arange(0,12).reshape(3,4)
print(array[::-1])

[[ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


25. The following array:

In [ ]:
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

transform to this array:

In [ ]:
array([[0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [57]:
array=np.ones((4,4))
print(np.pad(array, pad_width=1, constant_values=0))

[[0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]


26. The following array:

In [ ]:
array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

transform to the following:

In [ ]:
array([[10,  0, 10,  0, 10,  0],
       [ 5,  0,  5,  0,  5,  0],
       [10,  0, 10,  0, 10,  0],
       [ 5,  0,  5,  0,  5,  0],
       [10,  0, 10,  0, 10,  0],
       [ 5,  0,  5,  0,  5,  0]])

In [58]:
array=np.zeros((6,6))
array[::2,::2] = 10
array[1::2,1::2] = 5
print(array)

[[10.  0. 10.  0. 10.  0.]
 [ 0.  5.  0.  5.  0.  5.]
 [10.  0. 10.  0. 10.  0.]
 [ 0.  5.  0.  5.  0.  5.]
 [10.  0. 10.  0. 10.  0.]
 [ 0.  5.  0.  5.  0.  5.]]


27. Combine the following arrays into one as shown below and print it to the console.

In [59]:
A = np.arange(12).reshape(-1, 4)
B = np.array([[4, 3, 7, 2],
              [0, 5, 2, 6]])

In [63]:
print(np.append(A,B, axis=0))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 4  3  7  2]
 [ 0  5  2  6]]


28. Extract the same elements (intersection) of the arrays as a list and print result to the console.

In [64]:
A = np.arange(8).reshape(-1, 4)
B = np.array([[9, 10, 11, 3],
              [2, 8, 0, 9]])      


In [65]:
print(np.intersect1d(A, B))

[0 2 3]


29. Extract all unique values of this array as a list and print it to the console.


In [66]:
A = np.array([[5, 1, 2, 1, 2],
              [9, 1, 9, 7, 5],
              [4, 1, 5, 7, 9]])

In [67]:
print(np.unique(A))

[1 2 4 5 7 9]


30. Return a list of indexes with maximum values for each row from this array and print it to the console.

In [71]:
A = np.array([[0.4, 0.3, 0.3],
              [0.1, 0.1, 0.8],
              [0.2, 0.5, 0.3]])


In [72]:
print(np.argmax(A, axis=1))

[0 2 1]


31. Sort this array:
by row (ascending)
by column (ascending)
And print result to the console as shown below.

In [74]:
A = np.array(
    [[4.99, 3.49, 9.99], [1.99, 9.99, 4.99], [14.99, 2.39, 7.29]]
)

In [78]:
print(np.sort(A))
print(np.sort(A, axis=0))

[[ 3.49  4.99  9.99]
 [ 1.99  4.99  9.99]
 [ 2.39  7.29 14.99]]
[[ 1.99  2.39  4.99]
 [ 4.99  3.49  7.29]
 [14.99  9.99  9.99]]


32. Extract all elements from the following array with a value greater than 8 and print result to the console.


In [79]:
A = np.array(
    [[4.99, 3.49, 9.99], [1.99, 9.99, 4.99], [14.99, 2.39, 7.29]]
)

In [80]:
print(A[A>8])

[ 9.99  9.99 14.99]


33. Replace elements greater than 10 with a fixed value = 10.0 and print result to the console.

In [81]:
A = np.array(
    [
        [4.99, 3.49, 9.99],
        [1.99, 9.99, 14.99],
        [14.99, 2.39, 7.29],
    ]
)

In [83]:
print(np.where(A>10.0, 10.0, A))

[[ 4.99  3.49  9.99]
 [ 1.99  9.99 10.  ]
 [10.    2.39  7.29]]


34. Present the following two-dimensional array as a flattened one-dimensional array and print result to the console.


In [84]:
A = np.array(
    [
        [4.99, 3.49, 9.99],
        [1.99, 9.99, 14.99],
        [14.99, 2.39, 7.29],
    ]
)

In [85]:
print(np.ravel(A))

[ 4.99  3.49  9.99  1.99  9.99 14.99 14.99  2.39  7.29]


35. Using Numpy create an array of the same shape and data type as the given array and fill it with zeros. Print this array to the console.


In [86]:
A = np.array(
    [
        [4.99, 3.49, 9.99],
        [1.99, 9.99, 14.99],
        [14.99, 2.39, 7.29],
    ]
)

In [89]:
print(np.zeros_like(A))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


36. Using Numpy create an array of the same shape and data type as the given array and fill it with a constant value = 9.99. Print this array to the console.

In [90]:
A = np.array(
    [
        [4.99, 3.49, 9.99],
        [1.99, 9.99, 14.99],
        [14.99, 2.39, 7.29],
    ]
)

In [91]:
print(np.full_like(A, 9.99))

[[9.99 9.99 9.99]
 [9.99 9.99 9.99]
 [9.99 9.99 9.99]]


37. Using Numpy create a two-dimensional array (lower triangular matrix):

In [ ]:
array(
    [
        [1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]
    ]
)

In [92]:
print(np.tri(5, 5))

[[1. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0.]
 [1. 1. 1. 1. 1.]]


38. Using Numpy create any 3-dimensional array with shape (2, 3, 4) and assign to variable A.

In [ ]:
[[[4 5 4 2]
  [6 3 5 1]
  [5 2 1 2]]
 
 [[7 2 3 1]
  [6 2 0 9]
  [0 1 9 1]]]

In [94]:
A = np.arange(0,24).reshape((2,3,4))
print(A)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


39. Using Numpy create a two-dimensional array with shape of (200, 300) filled with random values from 0 to 255 (inclusive) with data type np.uint8 and assign to the variable image.

In [96]:
print(np.random.randint(low=0, high=256, size=(200,300), dtype=np.uint8))

[[249 167 170 ... 188 154   3]
 [138  20 194 ...  38  45  74]
 [242 108 221 ... 184  57 105]
 ...
 [180  55 112 ... 143 189 122]
 [ 21  11 118 ... 244 248 221]
 [219  87 125 ... 245 135 179]]


40. Sort this array along the rows in ascending order and assign to the variable image_sorted.


In [97]:
image = np.random.randint(
    low=0, high=256, size=(200, 300), dtype=np.uint8
)

In [101]:
image_sorted = np.sort(image)
print(image_sorted)

[[  0   1   2 ... 254 254 255]
 [  0   0   0 ... 254 255 255]
 [  1   2   2 ... 254 255 255]
 ...
 [  3   3   4 ... 253 255 255]
 [  0   1   5 ... 255 255 255]
 [  0   1   2 ... 253 254 254]]


41. Expand this array by one dimension (add a new dimension at the beginning). Expected shape of the output array: (1, 2, 3).
In response, print array to the console.

In [102]:
A = np.array([[4, 2, 1],
              [6, 4, 2]])


In [103]:
A=np.expand_dims(A,0)
print(A)

[[[4 2 1]
  [6 4 2]]]


42. Using Numpy create a three-dimensional array called image with shape (200, 300, 3) filled with random values from 0 to 255 (inclusive) and data type np.uint8. Set random seed to 42.
In response, print array to the console.

In [104]:
np.random.seed(42)
print(np.random.randint(0,256,(200,300,3),np.uint8))

[[[102 220 225]
  [ 95 179  61]
  [234 203  92]
  ...
  [ 41  27  87]
  [102 225  65]
  [170   0 238]]

 [[169 170 213]
  [159  44 250]
  [224 206  61]
  ...
  [162 118  77]
  [228  67  21]
  [ 68  30  64]]

 [[237  26 118]
  [ 62 157 198]
  [  1 151  37]
  ...
  [218 189  51]
  [193 250 243]
  [235  34 180]]

 ...

 [[116 102 228]
  [ 29  75  71]
  [156 133  53]
  ...
  [ 93  45  68]
  [124 238  76]
  [184 185 202]]

 [[216 202 116]
  [146 168 132]
  [236  80  45]
  ...
  [169 145 212]
  [123  50  70]
  [ 11  43  62]]

 [[ 32  52  65]
  [155   2  86]
  [ 83 240  27]
  ...
  [ 30  57 175]
  [ 72  83 171]
  [ 40 114 195]]]


43. Extend this array by one dimension (add a new dimension at the beginning) and assign to image_extended variable. Expected shape of this array is (1, 200, 300, 3).

In [105]:
image = np.random.randint(
    low=0, high=256, size=(200, 300, 3), dtype=np.uint8
)

In [106]:
print(np.expand_dims(image, 0))

[[[[145  30 244]
   [107   6 122]
   [201  42  86]
   ...
   [182 113 173]
   [140 196 105]
   [123  60 198]]

  [[221  40 190]
   [175  36 108]
   [ 33   0 106]
   ...
   [ 75 169  71]
   [218 180 159]
   [ 88  16   4]]

  [[141 115 148]
   [211  17 146]
   [118 201  37]
   ...
   [ 10 168 141]
   [136 119 180]
   [134 202  48]]

  ...

  [[105 148  18]
   [178 143 146]
   [249 136  32]
   ...
   [ 80  45 210]
   [182 138  93]
   [ 93 176 230]]

  [[  8  92  85]
   [105 188  47]
   [188 219 100]
   ...
   [117 202 126]
   [171 254  58]
   [ 60 227 231]]

  [[ 90  77 134]
   [121 220 235]
   [ 64 117 152]
   ...
   [ 60 122  47]
   [110 218 233]
   [233  85  89]]]]


44. Expand each of these arrays by adding one dimension at the beginning and then combine these arrays into one called images. Expected shape of images array: (2, 200, 300, 3).


In [107]:
image1 = np.random.randint(
    low=0, high=256, size=(200, 300, 3), dtype=np.uint8
)
image2 = np.random.randint(
    low=0, high=256, size=(200, 300, 3), dtype=np.uint8
)

In [109]:
image1=np.expand_dims(image1, 0)
image2=np.expand_dims(image2,0)
image=np.append(image1, image2, axis=0)
print(image)

[[[[[ 41 115 118]
    [ 84 233 122]
    [  9 233 198]
    ...
    [ 37  99 209]
    [211 120 126]
    [ 59  79  35]]

   [[136 156 232]
    [107 217 177]
    [129 224  85]
    ...
    [132  46 214]
    [107 200 163]
    [121  45 198]]

   [[ 58  69 203]
    [ 20  13 211]
    [254 145  72]
    ...
    [  6 183 128]
    [159 139  20]
    [217 117  31]]

   ...

   [[178  96 176]
    [178 151  78]
    [175 147 177]
    ...
    [169 200  37]
    [  9 171  29]
    [145 143  28]]

   [[189 185 126]
    [ 59  76 205]
    [  9 136  25]
    ...
    [ 62  31 235]
    [104 133 186]
    [154  50 165]]

   [[157 209 251]
    [181 230  48]
    [ 21 223 136]
    ...
    [ 76  88 111]
    [211 188  36]
    [ 23 111 239]]]]



 [[[[ 81  84 180]
    [239 195  87]
    [ 10 247 246]
    ...
    [ 49 136  91]
    [136 192 105]
    [  4 122 161]]

   [[121 115 195]
    [ 18   3 184]
    [253 169 244]
    ...
    [ 92 136 206]
    [ 89  89 113]
    [184   1  81]]

   [[198 236  19]
    [210  50 104]
    [ 12

45. Shape of this array is (1, 2, 3). Remove the unnecessary first dimension and extract (2, 3) array and print it to the console as shown below.

In [112]:
A = np.array([[[1, 2, 3], [6, 3, 2]]])

In [111]:
A=np.squeeze(A, 0)
print(A[0][1:])

[2 3]


46. Shape of this array is (4, 1). Remove the unnecessary dimension and extract (4, ) array and print result to the console.

In [114]:
A = np.array([[0.4], [0.9], [0.5], [0.6]])

In [117]:
A=np.squeeze(A,1)
print(A)

[0.4 0.9 0.5 0.6]


47. The following array is given:

In [118]:
A  = np.arange(12, dtype='int').reshape(-1, 4)

Using the slice operator, transform this array into the following:

In [ ]:
array(
    [
        [ 3,  2,  1,  0],
        [ 7,  6,  5,  4],
        [11, 10,  9,  8]
    ]


In [123]:
print(A[:,::-1])

[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]]


48. Using the slice operator, transform this array into the following:


In [ ]:
array(
    [
        [11, 10,  9,  8],
        [ 7,  6,  5,  4],
        [ 3,  2,  1,  0]
    ]
)

In [124]:
A = np.arange(12, dtype='int').reshape(-1, 4)

In [128]:
print(A[::-1,::-1])

[[11 10  9  8]
 [ 7  6  5  4]
 [ 3  2  1  0]]


49. Random seed is set to 42. The following array is given:Extract the first channel (index 0) of this image array and print it to the console.


In [129]:
np.random.seed(42)

image = np.random.randint(
    low=0, high=256, size=(10, 10, 3), dtype=np.uint8
)

In [134]:
print(image[0,:,:])

[[102 220 225]
 [ 95 179  61]
 [234 203  92]
 [  3  98 243]
 [ 14 149 245]
 [ 46 106 244]
 [ 99 187  71]
 [212 153 199]
 [188 174  65]
 [153  20  44]]


50. Extract any array of shape (5, 5, 3) from this array and assign to the result variable.


In [135]:
image = np.random.randint(
    low=0, high=256, size=(10, 10, 3), dtype=np.uint8
)


In [136]:
result = image[:5,:5,:]
print(image)

[[[129 219  27]
  [ 59  83 229]
  [ 41 175  91]
  [216 179  61]
  [110 213 173]
  [112 187  91]
  [234 174 198]
  [229  61  31]
  [171 189  40]
  [156 252 233]]

 [[195 126   7]
  [ 67  76 213]
  [174 175 205]
  [  8  34 160]
  [ 97  44 205]
  [ 56 201 232]
  [ 80 140  28]
  [100 163 103]
  [ 63  66  49]
  [  6 167  46]]

 [[103  15 155]
  [169 131  93]
  [ 95 193   1]
  [ 76 204  79]
  [253   3 215]
  [108 133  45]
  [ 35 133  53]
  [170  59  53]
  [105  52 245]
  [139   3 207]]

 [[ 84 145  53]
  [159  82  47]
  [220  37   4]
  [  8 190 178]
  [ 54 248 145]
  [249 159 215]
  [217  26 111]
  [198  43  22]
  [ 35 115 161]
  [  0 131 240]]

 [[201 144  40]
  [101 189 103]
  [ 19 229 227]
  [131  57 237]
  [ 13 249  15]
  [153  94 127]
  [ 46 186  47]
  [243 255 235]
  [ 14  45 152]
  [ 83 199 113]]

 [[167  22 205]
  [157   8 146]
  [214 238  43]
  [ 50 251 100]
  [ 85 133 248]
  [  3 148  11]
  [189  94  15]
  [246  39 217]
  [ 72  83 212]
  [ 94  51 216]]

 [[207  90 128]
  [ 99 236  